services:
  oauth_graphql:
    container_name: oauth_graphql
    depends_on:
      oauth_db:
        condition: service_healthy
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000

  oauth_db:
    container_name: graphql_database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 33300:3300
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 10s
      retries: 10
    devices:
      - "/dev/urandom:/dev/random"
volumes:
  mysql_data:
